### ISSUE TITLE
FullTick module ( GUI ) for Linux OS.

### ISSUE THREAD

**Issue by Thecarisma** [simple-lang/modules#3]
The fulltick dynamic module for simple-lang is a port of the fltk C++ gui library.  To build the dynmic module it has to be compiled against the simple.so and the fltk shared library

**Comment by Youngestdev** [comment]
So how do we accomplish this ? I have fltk installed in my OS.

**Comment by iamcoderisk** [comment]
How far have you gone with it?

**Comment by Youngestdev** [comment]
Well, real progress will start next week 😎.

**Comment by Youngestdev** [comment]
There's a  new update. It's been fixed already and currently undergoing further testing. Cheers :tada:

**Comment by Thecarisma** [comment]
> **This Repository is now Read-Only and the Issue has been moved to [https://github.com/simple-lang/simple/issues/16](https://github.com/simple-lang/simple/issues/16)**
