### ISSUE TITLE
Data Types Modules.

### ISSUE THREAD

**Issue by Youngestdev** [simple-lang/modules#4]
I'll be working on building data type modules such as List.sim and Number.sim.

# Reason.
Modules will enable us carry out basic operations in data type.

## Example
A list will be able to add, delete, reverse once the module is built.
``` Current list state
list = ["a", "b", test] 

display list +crlf
// Displays *a, b and test*
list.push("a")
// Undefined
```
## Result from this ?
Well, we'll have methods that arrays ( as in JavaScript ) or Lists ( as in Python ).
#### example :
```
.push()
.pop()
.reverse()
And so many more.
```

**Comment by Youngestdev** [comment]
Pheew. Update.
## The push method.
The push method has been built into two ways.
### 1. addToList(list, value).
This above, is a function to add a value to the List / Array. This function cannot be appended to the list variable directly. In this case, the list argument in the array stand for the array that an element will be added to and the value is that element ( number, string, list ) that'll be added to the array.
 I'll give an example.
``` Using the addToList function
call "simple/core/List.sim"
myList = ["a", "b"] # List containing two elements.
# Add the element `c` to the list / array.
addToList(myList, "c")
# `c` has been added to the list.
display myList // a, b, c
```
### 2. .push (x)
This is binded to the List class. To use this, you'll have to declare list using a class declaration structure. Take a look at the Example below:
``` The .push(x)
call "simple/core/List.sim"

myList = new List(["a", "b"])
# Let's add another value to the array..
myList.push("c")
display myList # a, b and c.
```
Unfortunately, I'm still working on the display of the keys in the list when called .
## Other methods
I've worked on other methods but are currently in function state, I'm rewriting them to fit the class structure type so they can be appended to the variable e.g myList.reverse()
I'll be sending a PR soon !

**Comment by Youngestdev** [comment]
# Update.
I've written some new methods.
+ `.indexOf()`
+ `.keys()`
+ An uncomplete `.sort()` and `.slice()` method - still under development.

## And Yes ! :tada: 
The List module has been pushed to the repo so it can be used from now on. More functionalities will be added soon.

**Comment by Thecarisma** [comment]
> **This Repository is now Read-Only and the Issue has been moved to [https://github.com/simple-lang/simple/issues/15](https://github.com/simple-lang/simple/issues/15)**
